export const allCountries = [
  { value: "af", name_ar: "أفغانستان", name_en: "Afghanistan" },
  { value: "al", name_ar: "ألبانيا", name_en: "Albania" },
  { value: "dz", name_ar: "الجزائر", name_en: "Algeria" },
  { value: "ad", name_ar: "أندورا", name_en: "Andorra" },
  { value: "ao", name_ar: "أنغولا", name_en: "Angola" },
  { value: "ar", name_ar: "الأرجنتين", name_en: "Argentina" },
  { value: "am", name_ar: "أرمينيا", name_en: "Armenia" },
  { value: "au", name_ar: "أستراليا", name_en: "Australia" },
  { value: "at", name_ar: "النمسا", name_en: "Austria" },
  { value: "az", name_ar: "أذربيجان", name_en: "Azerbaijan" },
  { value: "bs", name_ar: "جزر البهاما", name_en: "Bahamas" },
  { value: "bh", name_ar: "البحرين", name_en: "Bahrain" },
  { value: "bd", name_ar: "بنغلاديش", name_en: "Bangladesh" },
  { value: "bb", name_ar: "باربادوس", name_en: "Barbados" },
  { value: "by", name_ar: "بيلاروسيا", name_en: "Belarus" },
  { value: "be", name_ar: "بلجيكا", name_en: "Belgium" },
  { value: "bz", name_ar: "بليز", name_en: "Belize" },
  { value: "bj", name_ar: "بنين", name_en: "Benin" },
  { value: "bt", name_ar: "بوتان", name_en: "Bhutan" },
  { value: "bo", name_ar: "بوليفيا", name_en: "Bolivia" },
  { value: "ba", name_ar: "البوسنة والهرسك", name_en: "Bosnia and Herzegovina" },
  { value: "bw", name_ar: "بوتسوانا", name_en: "Botswana" },
  { value: "br", name_ar: "البرازيل", name_en: "Brazil" },
  { value: "bn", name_ar: "بروناي", name_en: "Brunei" },
  { value: "bg", name_ar: "بلغاريا", name_en: "Bulgaria" },
  { value: "bf", name_ar: "بوركينا فاسو", name_en: "Burkina Faso" },
  { value: "bi", name_ar: "بوروندي", name_en: "Burundi" },
  { value: "kh", name_ar: "كمبوديا", name_en: "Cambodia" },
  { value: "cm", name_ar: "الكاميرون", name_en: "Cameroon" },
  { value: "ca", name_ar: "كندا", name_en: "Canada" },
  { value: "cv", name_ar: "الرأس الأخضر", name_en: "Cape Verde" },
  {
    value: "cf",
    name_ar: "جمهورية أفريقيا الوسطى",
    name_en: "Central African Republic",
  },
  { value: "td", name_ar: "تشاد", name_en: "Chad" },
  { value: "cl", name_ar: "تشيلي", name_en: "Chile" },
  { value: "cn", name_ar: "الصين", name_en: "China" },
  { value: "co", name_ar: "كولومبيا", name_en: "Colombia" },
  { value: "km", name_ar: "جزر القمر", name_en: "Comoros" },
  { value: "cg", name_ar: "الكونغو", name_en: "Congo" },
  {
    value: "cd",
    name_ar: "جمهورية الكونغو الديمقراطية",
    name_en: "Democratic Republic of the Congo",
  },
  { value: "cr", name_ar: "كوستاريكا", name_en: "Costa Rica" },
  { value: "ci", name_ar: "ساحل العاج", name_en: "Ivory Coast" },
  { value: "hr", name_ar: "كرواتيا", name_en: "Croatia" },
  { value: "cu", name_ar: "كوبا", name_en: "Cuba" },
  { value: "cy", name_ar: "قبرص", name_en: "Cyprus" },
  { value: "cz", name_ar: "التشيك", name_en: "Czech Republic" },
  { value: "dk", name_ar: "الدنمارك", name_en: "Denmark" },
  { value: "dj", name_ar: "جيبوتي", name_en: "Djibouti" },
  { value: "dm", name_ar: "دومينيكا", name_en: "Dominica" },
  { value: "do", name_ar: "جمهورية الدومينيكان", name_en: "Dominican Republic" },
  { value: "ec", name_ar: "الإكوادور", name_en: "Ecuador" },
  { value: "eg", name_ar: "مصر", name_en: "Egypt" },
  { value: "sv", name_ar: "السلفادور", name_en: "El Salvador" },
  { value: "gq", name_ar: "غينيا الاستوائية", name_en: "Equatorial Guinea" },
  { value: "er", name_ar: "إريتريا", name_en: "Eritrea" },
  { value: "ee", name_ar: "إستونيا", name_en: "Estonia" },
  { value: "et", name_ar: "إثيوبيا", name_en: "Ethiopia" },
  { value: "fj", name_ar: "فيجي", name_en: "Fiji" },
  { value: "fi", name_ar: "فنلندا", name_en: "Finland" },
  { value: "fr", name_ar: "فرنسا", name_en: "France" },
  { value: "ga", name_ar: "الغابون", name_en: "Gabon" },
  { value: "gm", name_ar: "غامبيا", name_en: "Gambia" },
  { value: "ge", name_ar: "جورجيا", name_en: "Georgia" },
  { value: "de", name_ar: "ألمانيا", name_en: "Germany" },
  { value: "gh", name_ar: "غانا", name_en: "Ghana" },
  { value: "gr", name_ar: "اليونان", name_en: "Greece" },
  { value: "gd", name_ar: "غرينادا", name_en: "Grenada" },
  { value: "gt", name_ar: "غواتيمالا", name_en: "Guatemala" },
  { value: "gn", name_ar: "غينيا", name_en: "Guinea" },
  { value: "gw", name_ar: "غينيا بيساو", name_en: "Guinea-Bissau" },
  { value: "gy", name_ar: "غيانا", name_en: "Guyana" },
  { value: "ht", name_ar: "هايتي", name_en: "Haiti" },
  { value: "hn", name_ar: "هندوراس", name_en: "Honduras" },
  { value: "hu", name_ar: "المجر", name_en: "Hungary" },
  { value: "is", name_ar: "آيسلندا", name_en: "Iceland" },
  { value: "in", name_ar: "الهند", name_en: "India" },
  { value: "id", name_ar: "إندونيسيا", name_en: "Indonesia" },
  { value: "ir", name_ar: "إيران", name_en: "Iran" },
  { value: "iq", name_ar: "العراق", name_en: "Iraq" },
  { value: "ie", name_ar: "أيرلندا", name_en: "Ireland" },
  { value: "it", name_ar: "إيطاليا", name_en: "Italy" },
  { value: "jm", name_ar: "جامايكا", name_en: "Jamaica" },
  { value: "jp", name_ar: "اليابان", name_en: "Japan" },
  { value: "je", name_ar: "جيرسي", name_en: "Jersey" },
  { value: "jo", name_ar: "الأردن", name_en: "Jordan" },
  { value: "kz", name_ar: "كازاخستان", name_en: "Kazakhstan" },
  { value: "ke", name_ar: "كينيا", name_en: "Kenya" },
  { value: "ki", name_ar: "كيريباتي", name_en: "Kiribati" },
  { value: "kp", name_ar: "كوريا الشمالية", name_en: "North Korea" },
  { value: "kr", name_ar: "كوريا الجنوبية", name_en: "South Korea" },
  { value: "kw", name_ar: "الكويت", name_en: "Kuwait" },
  { value: "kg", name_ar: "قيرغيزستان", name_en: "Kyrgyzstan" },
  { value: "la", name_ar: "لاوس", name_en: "Laos" },
  { value: "lv", name_ar: "لاتفيا", name_en: "Latvia" },
  { value: "lb", name_ar: "لبنان", name_en: "Lebanon" },
  { value: "ls", name_ar: "ليسوتو", name_en: "Lesotho" },
  { value: "lr", name_ar: "ليبيريا", name_en: "Liberia" },
  { value: "ly", name_ar: "ليبيا", name_en: "Libya" },
  { value: "li", name_ar: "ليختنشتاين", name_en: "Liechtenstein" },
  { value: "lt", name_ar: "ليتوانيا", name_en: "Lithuania" },
  { value: "lu", name_ar: "لوكسمبورغ", name_en: "Luxembourg" },
  { value: "mo", name_ar: "ماكاو", name_en: "Macao" },
  { value: "mg", name_ar: "مدغشقر", name_en: "Madagascar" },
  { value: "mw", name_ar: "مالاوي", name_en: "Malawi" },
  { value: "my", name_ar: "ماليزيا", name_en: "Malaysia" },
  { value: "mv", name_ar: "جزر المالديف", name_en: "Maldives" },
  { value: "ml", name_ar: "مالي", name_en: "Mali" },
  { value: "mt", name_ar: "مالطا", name_en: "Malta" },
  { value: "mh", name_ar: "جزر مارشال", name_en: "Marshall Islands" },
  { value: "mq", name_ar: "مارتينيك", name_en: "Martinique" },
  { value: "mr", name_ar: "موريتانيا", name_en: "Mauritania" },
  { value: "mu", name_ar: "موريشيوس", name_en: "Mauritius" },
  { value: "yt", name_ar: "مايوت", name_en: "Mayotte" },
  { value: "mx", name_ar: "المكسيك", name_en: "Mexico" },
  { value: "fm", name_ar: "ميكرونيزيا", name_en: "Micronesia" },
  { value: "md", name_ar: "مولدوفا", name_en: "Moldova" },
  { value: "mc", name_ar: "موناكو", name_en: "Monaco" },
  { value: "mn", name_ar: "منغوليا", name_en: "Mongolia" },
  { value: "me", name_ar: "الجبل الأسود", name_en: "Montenegro" },
  { value: "ms", name_ar: "مونتسيرات", name_en: "Montserrat" },
  { value: "ma", name_ar: "المغرب", name_en: "Morocco" },
  { value: "mz", name_ar: "موزمبيق", name_en: "Mozambique" },
  { value: "mm", name_ar: "ميانمار", name_en: "Myanmar" },
  { value: "na", name_ar: "ناميبيا", name_en: "Namibia" },
  { value: "nr", name_ar: "ناورو", name_en: "Nauru" },
  { value: "np", name_ar: "نيبال", name_en: "Nepal" },
  { value: "nl", name_ar: "هولندا", name_en: "Netherlands" },
  { value: "nc", name_ar: "كاليدونيا الجديدة", name_en: "New Caledonia" },
  { value: "nz", name_ar: "نيوزيلندا", name_en: "New Zealand" },
  { value: "ni", name_ar: "نيكاراغوا", name_en: "Nicaragua" },
  { value: "ne", name_ar: "النيجر", name_en: "Niger" },
  { value: "ng", name_ar: "نيجيريا", name_en: "Nigeria" },
  { value: "nu", name_ar: "نيوي", name_en: "Niue" },
  { value: "nf", name_ar: "جزيرة نورفولك", name_en: "Norfolk Island" },
  { value: "mk", name_ar: "مقدونيا الشمالية", name_en: "North Macedonia" },
  {
    value: "mp",
    name_ar: "جزر ماريانا الشمالية",
    name_en: "Northern Mariana Islands",
  },
  { value: "no", name_ar: "النرويج", name_en: "Norway" },
  { value: "om", name_ar: "عمان", name_en: "Oman" },
  { value: "pk", name_ar: "باكستان", name_en: "Pakistan" },
  { value: "pw", name_ar: "بالاو", name_en: "Palau" },
  { value: "ps", name_ar: "فلسطين", name_en: "Palestine" },
  { value: "pa", name_ar: "بنما", name_en: "Panama" },
  { value: "pg", name_ar: "بابوا غينيا الجديدة", name_en: "Papua New Guinea" },
  { value: "py", name_ar: "باراغواي", name_en: "Paraguay" },
  { value: "pe", name_ar: "بيرو", name_en: "Peru" },
  { value: "ph", name_ar: "الفلبين", name_en: "Philippines" },
  { value: "pn", name_ar: "بيتكيرن", name_en: "Pitcairn" },
  { value: "pl", name_ar: "بولندا", name_en: "Poland" },
  { value: "pt", name_ar: "البرتغال", name_en: "Portugal" },
  { value: "pr", name_ar: "بورتوريكو", name_en: "Puerto Rico" },
  { value: "qa", name_ar: "قطر", name_en: "Qatar" },
  { value: "re", name_ar: "روينيون", name_en: "Reunion" },
  { value: "ro", name_ar: "رومانيا", name_en: "Romania" },
  { value: "ru", name_ar: "روسيا", name_en: "Russia" },
  { value: "rw", name_ar: "رواندا", name_en: "Rwanda" },
  { value: "bl", name_ar: "سانت بارتيليمي", name_en: "Saint Barthelemy" },
  { value: "sh", name_ar: "سانت هيلانة", name_en: "Saint Helena" },
  { value: "kn", name_ar: "سانت كيتس ونيفيس", name_en: "Saint Kitts and Nevis" },
  { value: "lc", name_ar: "سانت لوسيا", name_en: "Saint Lucia" },
  { value: "mf", name_ar: "سانت مارتين", name_en: "Saint Martin" },
  {
    value: "pm",
    name_ar: "سانت بيير وميكلون",
    name_en: "Saint Pierre and Miquelon",
  },
  {
    value: "vc",
    name_ar: "سانت فنسنت والغرينادين",
    name_en: "Saint Vincent and the Grenadines",
  },
  { value: "ws", name_ar: "ساموا", name_en: "Samoa" },
  { value: "sm", name_ar: "سان مارينو", name_en: "San Marino" },
  { value: "st", name_ar: "ساو تومي وبرينسيب", name_en: "Sao Tome and Principe" },
  { value: "sa", name_ar: "السعودية", name_en: "Saudi Arabia" },
  { value: "sn", name_ar: "السنغال", name_en: "Senegal" },
  { value: "rs", name_ar: "صربيا", name_en: "Serbia" },
  { value: "sc", name_ar: "سيشل", name_en: "Seychelles" },
  { value: "sl", name_ar: "سيراليون", name_en: "Sierra Leone" },
  { value: "sg", name_ar: "سنغافورة", name_en: "Singapore" },
  { value: "sx", name_ar: "سينت مارتن", name_en: "Sint Maarten" },
  { value: "sk", name_ar: "سلوفاكيا", name_en: "Slovakia" },
  { value: "si", name_ar: "سلوفينيا", name_en: "Slovenia" },
  { value: "sb", name_ar: "جزر سليمان", name_en: "Solomon Islands" },
  { value: "so", name_ar: "الصومال", name_en: "Somalia" },
  { value: "za", name_ar: "جنوب أفريقيا", name_en: "South Africa" },
  {
    value: "gs",
    name_ar: "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
    name_en: "South Georgia and the South Sandwich Islands",
  },
  { value: "ss", name_ar: "جنوب السودان", name_en: "South Sudan" },
  { value: "es", name_ar: "إسبانيا", name_en: "Spain" },
  { value: "lk", name_ar: "سريلانكا", name_en: "Sri Lanka" },
  { value: "sd", name_ar: "السودان", name_en: "Sudan" },
  { value: "sr", name_ar: "سورينام", name_en: "Suriname" },
  {
    value: "sj",
    name_ar: "سفالبارد ويان ماين",
    name_en: "Svalbard and Jan Mayen",
  },
  { value: "se", name_ar: "السويد", name_en: "Sweden" },
  { value: "ch", name_ar: "سويسرا", name_en: "Switzerland" },
  { value: "sy", name_ar: "سوريا", name_en: "Syria" },
  { value: "tw", name_ar: "تايوان", name_en: "Taiwan" },
  { value: "tj", name_ar: "طاجيكستان", name_en: "Tajikistan" },
  { value: "tz", name_ar: "تنزانيا", name_en: "Tanzania" },
  { value: "th", name_ar: "تايلاند", name_en: "Thailand" },
  { value: "tl", name_ar: "تيمور الشرقية", name_en: "Timor-Leste" },
  { value: "tg", name_ar: "توغو", name_en: "Togo" },
  { value: "tk", name_ar: "توكيلاو", name_en: "Tokelau" },
  { value: "to", name_ar: "تونغا", name_en: "Tonga" },
  { value: "tt", name_ar: "ترينيداد وتوباغو", name_en: "Trinidad and Tobago" },
  { value: "tn", name_ar: "تونس", name_en: "Tunisia" },
  { value: "tr", name_ar: "تركيا", name_en: "Turkey" },
  { value: "tm", name_ar: "تركمانستان", name_en: "Turkmenistan" },
  {
    value: "tc",
    name_ar: "جزر توركس وكايكوس",
    name_en: "Turks and Caicos Islands",
  },
  { value: "tv", name_ar: "توفالو", name_en: "Tuvalu" },
  { value: "ug", name_ar: "أوغندا", name_en: "Uganda" },
  { value: "ua", name_ar: "أوكرانيا", name_en: "Ukraine" },
  {
    value: "ae",
    name_ar: "الإمارات العربية المتحدة",
    name_en: "United Arab Emirates",
  },
  { value: "gb", name_ar: "المملكة المتحدة", name_en: "United Kingdom" },
  { value: "us", name_ar: "الولايات المتحدة", name_en: "United States" },
  {
    value: "um",
    name_ar: "جزر الولايات المتحدة البعيدة الصغيرة",
    name_en: "United States Minor Outlying Islands",
  },
  { value: "uy", name_ar: "أوروغواي", name_en: "Uruguay" },
  { value: "uz", name_ar: "أوزبكستان", name_en: "Uzbekistan" },
  { value: "VU", name_ar: "فانواتو", name_en: "Vanuatu" },
  { value: "VE", name_ar: "فنزويلا", name_en: "Venezuela" },
  { value: "VN", name_ar: "فيتنام", name_en: "Vietnam" },
  {
    value: "VG",
    name_ar: "جزر فيرجن البريطانية",
    name_en: "British Virgin Islands",
  },
  { value: "VI", name_ar: "جزر فيرجن الأمريكية", name_en: "U.S. Virgin Islands" },
  { value: "WF", name_ar: "واليس وفوتونا", name_en: "Wallis and Futuna" },
  { value: "EH", name_ar: "الصحراء الغربية", name_en: "Western Sahara" },
  { value: "YE", name_ar: "اليمن", name_en: "Yemen" },
  { value: "ZM", name_ar: "زامبيا", name_en: "Zambia" },
  { value: "ZW", name_ar: "زيمبابوي", name_en: "Zimbabwe" },
];




export const getSpecificCountry = ( iso ) => {

 if(iso) return allCountries.find((item) => item.val.toLowerCase() == iso?.toLowerCase())

}


 